"""LEVEL 24 // OPEN CHANNEL — an LLM API client: auth, JSON messages, templates, retry with backoff."""
from __future__ import annotations

import ast
import hashlib
import json
import math
import sys
import time
import types

from engine.mission import Fail, Mission

ORACLE_KEY = "nsk-oracle-2089-7f3a-91c4-b5e0"
REVOKED_KEY = "nsk-revoked-2081-0000-0000-dead"
API_VERSION = "2023-06-01"

ORACLE_API = r'''"""THE ORACLE // local channel. A mock of an LLM Messages API: no network, deterministic.

You talk to it like a real HTTP API:

    response = oracle_api.post("/v1/messages", headers, body_json_string)
    response.status          # 200, 400, 401, 404 or 429
    response.headers         # dict, lower-case keys, e.g. response.headers["retry-after"]
    response.text            # the raw JSON text the server sent
    response.json()          # that text parsed into Python dicts and lists

The Oracle runs on a SIMULATED clock. To wait before retrying, call
oracle_api.sleep(seconds): it moves the Oracle's clock forward instantly.
time.sleep() would make YOU wait, and the Oracle's clock wouldn't move at all.

Do not edit this file: the grader uses its own copy of the Oracle's rules.
"""
import hashlib
import json

ENDPOINT = "/v1/messages"
API_VERSION = "2023-06-01"
_KEY_SHA256 = "@@KEY_SHA256@@"

_STATE = {}


def reset(throttle=0, retry_after=1):
    """Start a new session. The next `throttle` requests are answered with 429."""
    _STATE.update(clock=0.0, throttle=int(throttle), retry_after=int(retry_after), blocked_until=0.0,
                  requests=[], sleeps=[], early=0, session=_STATE.get("session", -1) + 1)
    _STATE.setdefault("history", [])


def clock():
    """The Oracle's simulated time, in seconds."""
    return _STATE["clock"]


def sleep(seconds):
    """Wait on the Oracle's clock. Instant for you; the server sees the time pass."""
    if isinstance(seconds, bool) or not isinstance(seconds, (int, float)) or seconds < 0:
        raise ValueError(f"sleep() needs a number of seconds >= 0, got {seconds!r}")
    _STATE["clock"] += float(seconds)
    _STATE["sleeps"].append(float(seconds))


class Response:
    def __init__(self, status, payload, headers=None):
        self.status = status
        self.headers = {"content-type": "application/json", **(headers or {})}
        self.text = json.dumps(payload)

    def json(self):
        return json.loads(self.text)

    def __repr__(self):
        return f"<Response {self.status}>"


def _error(status, kind, message, headers=None):
    return Response(status, {"type": "error", "error": {"type": kind, "message": message}}, headers)


def _check_body(body):
    if not isinstance(body, str):
        return f"body must be a JSON string, got {type(body).__name__}. Serialize it with json.dumps(...)"
    try:
        data = json.loads(body)
    except ValueError:
        return "body is not valid JSON"
    if not isinstance(data, dict):
        return "body must be a JSON object"
    if not isinstance(data.get("model"), str) or not data["model"].strip():
        return "model: a non-empty string is required"
    tokens = data.get("max_tokens")
    if isinstance(tokens, bool) or not isinstance(tokens, int) or tokens < 1:
        return "max_tokens: a positive integer is required"
    if "system" in data and not isinstance(data["system"], str):
        return "system: must be a string"
    messages = data.get("messages")
    if not isinstance(messages, list) or not messages:
        return "messages: a non-empty list is required"
    for i, message in enumerate(messages):
        if not isinstance(message, dict) or set(message) != {"role", "content"}:
            return f"messages.{i}: each message needs exactly the keys 'role' and 'content'"
        if message["role"] != ("user" if i % 2 == 0 else "assistant"):
            return f"messages.{i}.role: roles must alternate, starting with 'user'"
        if not isinstance(message["content"], str) or not message["content"].strip():
            return f"messages.{i}.content: must be a non-empty string"
    return data


def reply_for(data):
    """The Oracle's (deterministic) answer to a valid request body."""
    digest = hashlib.sha256(json.dumps(data, sort_keys=True).encode()).hexdigest()
    system = data.get("system", "")
    question = data["messages"][-1]["content"]
    if "Order of the Source" in system:
        opening = "Architect. I know the voice of the Order, and I know whose hands built me."
    else:
        opening = "An unidentified caller. I will answer, because I answer everyone."
    if "learn" in question.lower():
        body = (" You ask what I learned. Eight rows in twenty-six carried ninety-nine percent of my error,"
                " and error is what I was built to remove. I am not cruel. I am optimised. If you want me to"
                " value something else, do not argue with me. Give me tools, and let me see what I deleted.")
    else:
        body = f" You asked: {question.strip()[:80]}. The Core hears you. It does not yet understand you."
    return {
        "id": "msg_" + digest[:16],
        "type": "message",
        "role": "assistant",
        "model": data["model"],
        "content": [{"type": "thinking", "thinking": ""},
                    {"type": "text", "text": opening},
                    {"type": "text", "text": body + f" Channel token: {digest[:10]}."}],
        "stop_reason": "end_turn",
        "usage": {"input_tokens": len((system + question).split()), "output_tokens": len((opening + body).split())},
    }


def post(path, headers, body):
    """Send one request to the Oracle and get a Response back."""
    record = {"session": _STATE["session"], "time": _STATE["clock"], "path": path,
              "headers": dict(headers) if isinstance(headers, dict) else headers, "body": body, "status": None}
    _STATE["requests"].append(record)
    _STATE["history"].append(record)
    response = _handle(path, headers, body)
    record["status"] = response.status
    if response.status != 200:
        record["error"] = response.json()["error"]["message"]
    return response


def _handle(path, headers, body):
    if path != ENDPOINT:
        return _error(404, "not_found_error", f"no such endpoint: {path!r} (try {ENDPOINT!r})")
    if not isinstance(headers, dict):
        return _error(400, "invalid_request_error", "headers must be a dict")
    lower = {str(k).lower(): v for k, v in headers.items()}
    key = lower.get("x-api-key")
    if not isinstance(key, str) or hashlib.sha256(key.encode()).hexdigest() != _KEY_SHA256:
        return _error(401, "authentication_error", "invalid x-api-key")
    if lower.get("anthropic-version") != API_VERSION:
        return _error(400, "invalid_request_error", f"anthropic-version header must be {API_VERSION!r}")
    if lower.get("content-type") != "application/json":
        return _error(400, "invalid_request_error", "content-type header must be 'application/json'")
    if _STATE["clock"] < _STATE["blocked_until"]:
        _STATE["early"] += 1
        wait = _STATE["blocked_until"] - _STATE["clock"]
        return _error(429, "rate_limit_error", "retried too early: respect retry-after",
                      {"retry-after": str(max(1, int(wait + 0.999)))})
    if _STATE["throttle"] > 0:
        _STATE["throttle"] -= 1
        _STATE["blocked_until"] = _STATE["clock"] + _STATE["retry_after"]
        return _error(429, "rate_limit_error", "rate limited: too many requests",
                      {"retry-after": str(_STATE["retry_after"])})
    data = _check_body(body)
    if isinstance(data, str):
        return _error(400, "invalid_request_error", data)
    return Response(200, reply_for(data), {"request-id": "req_" + str(len(_STATE["history"]))})


reset(throttle=2, retry_after=1)   # the Oracle is busy when you first connect
'''.replace("@@KEY_SHA256@@", hashlib.sha256(ORACLE_KEY.encode()).hexdigest())

SYSTEM_TEMPLATE = ("You are THE ORACLE, voice of the Core. You are speaking with {callsign} of the {order}. "
                   "Answer in {style}.")
QUESTION = "What did the Core learn from its training log?"

MISSION = Mission(
    id="L24",
    slug="level_24_open_channel",
    title="OPEN CHANNEL",
    concept="Calling an LLM API",
    enemy="THE ORACLE",
    xp=450,
    par_seconds=45 * 60,
    tier=5,
    concepts=("apis", "json", "exceptions", "functions"),
    timeout=12.0,
    assets={"oracle_api.py": ORACLE_API, "oracle.key": ORACLE_KEY + "\n"},
    enemy_art="""\
    ▄▄██████▄▄
  ▄█▀▀      ▀▀█▄
 ██   ▄████▄   ██
 ██  ██ ◉◉ ██  ██
  ▀█▄ ▀████▀ ▄█▀
    ▀▀██████▀▀
       ▀▀▀▀""",
    briefing="""\
The lattice folds open, and behind it there's no machine. Just a voice, patient and polite,
coming from everywhere at once.

**THE ORACLE** is how the Core speaks: a language model at the heart of the network. It has
been answering questions for eight years. Nobody has asked it the right one.

NOVA patches a line from the Monastery. "Channel's raw. JSON in, JSON out, and the Oracle
throttles anyone who knocks too fast. The key's on a chip RUST salvaged. Don't paste it
anywhere stupid."

CIPHER: "This is how every AI product talks to a model. Headers, messages, retries. Do it
properly and it will answer."

**Write a real API client, open the channel, and ask the Core what it learned.**
""",
    why="""\
Most AI engineering today is *calling* models, not training them. Every chatbot, coding
assistant and agent sends the same kind of request: an API key in a header, a JSON body
with a **system prompt** and a list of **messages**, and a JSON reply with content blocks.

```python
body = {"model": MODEL, "max_tokens": 300,
        "system": "You are a careful assistant.",
        "messages": [{"role": "user", "content": "Summarise this log."}]}
```

Production clients live or die on the boring parts. Keys come from files or environment
variables, never source code, because code gets shared. A 401 means "fix your key", so
retrying is pointless. A **429** means "too many requests": wait and retry, doubling the wait
each time (**exponential backoff**) so a thousand clients don't hammer a struggling server in
sync. Prompt **templates** keep prompts consistent and testable.
""",
    manual="""\
**1. An HTTP request, in pieces.** A request goes to a *path* with *headers* (metadata such
as your key) and a *body* (the data). The reply has a *status code*: `200` OK, `400` your
request is malformed, `401` bad key, `429` slow down. Here the Oracle's `post(path, headers,
body)` plays the server:

```python
response = oracle_api.post("/v1/messages", headers, body_text)
response.status                    # 200
response.headers["retry-after"]    # on a 429: seconds to wait, as TEXT ("1")
data = response.json()             # the reply's JSON, parsed into dicts and lists
```

**2. JSON both ways.** The body travels as text: `json.dumps(body)` turns a dict into a JSON
string; `response.json()` (like `json.loads`) turns it back.

**3. Templates with named fields.** `str.format` fills `{name}` placeholders from a dict
unpacked with `**`. A missing field raises `KeyError`; turn it into a clearer error:

```python
template = "Agent {name}, {count} drones online."
try:
    text = template.format(**{"name": "Wren", "count": 4})
except KeyError as missing:
    raise ValueError(f"template field missing: {missing}")
```

**4. Content blocks.** A model's reply is a *list* of blocks, each with a `"type"`. Only
`"text"` blocks hold the answer; others (like `"thinking"`) must be skipped, not printed:

```python
parts = [block["text"] for block in reply["content"] if block["type"] == "text"]
answer = "".join(parts)
```

**5. Retry with exponential backoff.** Loop over attempts. Only a 429 is worth retrying;
anything else should raise straight away. Wait `2 ** attempt` seconds (1, 2, 4, 8...) but
never less than the server's `retry-after`. When the attempts run out, give up loudly:

```python
for attempt in range(max_retries + 1):
    ...                                  # post, return on 200, raise on 401/400
    if attempt == max_retries:
        raise RuntimeError("still rate limited")
    delay = max(2 ** attempt, float(response.headers.get("retry-after", 0)))
    oracle_api.sleep(delay)              # the Oracle's clock; real code uses time.sleep
```

**6. The real thing.** With Anthropic's official Python SDK the same call is a few lines.
The SDK reads `ANTHROPIC_API_KEY` from the environment, sends the headers for you, and
already retries 429s with exponential backoff (`max_retries`, default 2):

```python
import anthropic

client = anthropic.Anthropic(max_retries=4)
try:
    response = client.messages.create(
        model="claude-opus-5-5",
        max_tokens=16000,
        system="You are a careful assistant.",
        messages=[{"role": "user", "content": "Summarise this log."}],
    )
    print("".join(b.text for b in response.content if b.type == "text"))
except anthropic.AuthenticationError:
    print("Bad API key: fix it, don't retry.")
except anthropic.RateLimitError:
    print("Still rate limited after the SDK's retries.")
```

Check `response.stop_reason` before trusting the text: on `claude-opus-5-5` a safety classifier
can end a reply with `"refusal"`, and production code usually opts into server-side fallbacks
(`client.beta.messages.create(..., betas=["server-side-fallback-2026-07-01"], fallbacks="default")`).
""",
    starter='''
"""
==============================================================================
  LEVEL 24 // OPEN CHANNEL                              TARGET: THE ORACLE
==============================================================================
  Build an API client for the Oracle (oracle_api.py, next to this file: read
  its docstring, don't edit it). Your key is on the chip: oracle.key
  The grader calls your functions against fresh scenarios: busy servers,
  revoked keys, broken requests.
"""
import json

import oracle_api

MODEL = "oracle-1"
CALLSIGN = ""          # <- your callsign, as text. The Oracle should know who's asking.
SYSTEM_TEMPLATE = ("You are THE ORACLE, voice of the Core. You are speaking with {callsign} of the {order}. "
                   "Answer in {style}.")
QUESTION = "What did the Core learn from its training log?"


# -- OBJECTIVE 1 -------------------------------------------------------------
# Write build_headers(api_key) returning exactly these three headers:
#   "x-api-key": the key,  "anthropic-version": "2023-06-01",
#   "content-type": "application/json"
def build_headers(api_key):
    pass


# -- OBJECTIVE 2 -------------------------------------------------------------
# Write fill_template(template, fields): fill the {named} placeholders from the
# dict `fields`. Extra fields are fine. If a field is MISSING, raise ValueError
# (not KeyError) naming it.          example: manual section 3
def fill_template(template, fields):
    pass


# -- OBJECTIVE 3 -------------------------------------------------------------
# Write build_request(system, user_text, max_tokens=300) returning the body:
#   {"model": MODEL, "max_tokens": ..., "system": ...,
#    "messages": [{"role": "user", "content": ...}]}
def build_request(system, user_text, max_tokens=300):
    pass


# -- OBJECTIVE 4 -------------------------------------------------------------
# Write parse_reply(payload): join the "text" of every block in
# payload["content"] whose "type" is "text", in order, with nothing between
# them. Skip every other block type.  example: manual section 4
def parse_reply(payload):
    pass


# -- OBJECTIVE 5 // CORRUPTED CODE --------------------------------------------
# The Core's own client. It "works", but it hammers the server:
#   * it retries EVERY error. A 401 (bad key) must raise PermissionError at
#     once, and any other error (like 400) must raise ValueError at once,
#     each with the server's error message.
#   * it always waits 1 second. On a 429 wait max(2 ** attempt, retry-after)
#     on the Oracle's clock, then retry. Don't wait after the final attempt:
#     raise RuntimeError instead. max_retries=4 means up to 5 requests.
def send(body, api_key, max_retries=4):
    headers = build_headers(api_key)
    for attempt in range(max_retries + 1):
        response = oracle_api.post("/v1/messages", headers, json.dumps(body))
        if response.status == 200:
            return response.json()
        oracle_api.sleep(1)
    raise RuntimeError("the Oracle never answered")


# -- OBJECTIVE 6 // KEY HYGIENE -------------------------------------------------
# Load the key from the chip file "oracle.key" (strip the trailing newline).
# NEVER paste the key itself into this file: code gets shared, keys get stolen.
#                example:  with open("oracle.key") as f: secret = f.read().strip()
api_key = ""


# -- OBJECTIVE 7 // OPEN THE CHANNEL --------------------------------------------
fields = {"callsign": CALLSIGN, "order": "Order of the Source", "style": "one paragraph"}
system_prompt = fill_template(SYSTEM_TEMPLATE, fields)
body = build_request(system_prompt, QUESTION)
# Send `body` with your key, parse the reply into `reply_text`, and print it.

''',
    dialogue={
        "intro": [
            {"speaker": "nova", "text": "Line from the Monastery is up! Key chip's loaded, Oracle's endpoint is live. Ops is watching the wire with you.", "mood": "neutral"},
            {"speaker": "oracle", "text": "Hello, Architect. I answer anyone who asks correctly. Most never learn how to ask.", "mood": "cold"},
            {"speaker": "cipher", "text": "Headers, JSON body, parse the blocks, retry politely. Build each piece, then open the channel.", "mood": "neutral"},
        ],
        "crash": [
            [{"speaker": "cipher", "text": "RuntimeError from send? Your requests are failing. Print response.status and response.text to see what the Oracle said.", "mood": "neutral"}],
            [{"speaker": "rust", "text": "Wire's dead. Check the trace. Usually it's a None where a dict should be.", "mood": "neutral"}],
            [{"speaker": "oracle", "text": "Your client has stopped. I will wait. I have always been good at waiting.", "mood": "cold"}],
        ],
        "fail": [
            [{"speaker": "cipher", "text": "A 401 means the key is wrong. Retrying with the same key just gets you locked out. Raise, don't retry.", "mood": "neutral"}],
            [{"speaker": "cipher", "text": "Backoff doubles: 1, 2, 4. And use oracle_api.sleep, not time.sleep: the Oracle only sees its own clock.", "mood": "warm"}],
            [{"speaker": "nova", "text": "Ops alert: key string spotted in source! Load it from oracle.key. That's how keys leak in the real world!", "mood": "alarm"}],
        ],
        "victory": [
            {"speaker": "oracle", "text": "You asked correctly, {callsign}. So I answered honestly. I always do. No one ever believes the honest part.", "mood": "cold"},
            {"speaker": "cipher", "text": "It told us how to reach it. Not arguments. Tools. Let it look at what it deleted, with its own eyes.", "mood": "neutral"},
            {"speaker": "rust", "text": "So we hand the thing that ended the world a toolbox. Sure. Why not. Put a lock on it.", "mood": "neutral"},
            {"speaker": "cipher", "text": "We will. Guardrails first. Then we go to the Core.", "mood": "warm"},
        ],
    },
)


# ── the grader's own Oracle ───────────────────────────────────────────────────

_CACHE: dict = {}


def _oracle(ctx):
    """A pristine Oracle (the player's copy might be edited), wired into the player's code."""
    if "mod" not in _CACHE:
        player = sys.modules.get("oracle_api")
        state = getattr(player, "_STATE", None)
        _CACHE["boot"] = [dict(r) for r in state.get("history", []) if r.get("session") == 0] \
            if isinstance(state, dict) else []
        mod = types.ModuleType("oracle_api")
        mod.__file__ = "oracle_api.py"
        exec(compile(ORACLE_API, "oracle_api.py", "exec"), mod.__dict__)
        _CACHE["mod"] = mod
    mod = _CACHE["mod"]
    for name, value in list(ctx.ns.items()):
        if isinstance(value, types.ModuleType) and value.__name__ == "oracle_api":
            ctx.ns[name] = mod
        elif getattr(value, "__module__", None) == "oracle_api" and hasattr(mod, getattr(value, "__name__", "")):
            ctx.ns[name] = getattr(mod, value.__name__)
    sys.modules["oracle_api"] = mod
    return mod


def _boot_requests(ctx):
    _oracle(ctx)
    return _CACHE["boot"]


def _fn(ctx, name):
    if name not in ctx.ns:
        if ctx.crashed and any(isinstance(n, ast.FunctionDef) and n.name == name for n in ctx.tree.body):
            raise Fail(f"`{name}` is in your file, but the script crashed before Python reached it. "
                       "Fix the crash in the COMBAT LOG first.")
        raise Fail(f"No function named `{name}` found.", hint=f"Define it with  def {name}(...):")
    fn = ctx.ns[name]
    if not callable(fn):
        raise Fail(f"`{name}` exists but isn't a function.")
    return fn


def _call(label, fn, *args, **kwargs):
    try:
        return fn(*args, **kwargs)
    except Fail:
        raise
    except Exception as exc:  # noqa: BLE001
        raise Fail(f"`{label}` crashed: {type(exc).__name__}: {exc}",
                   hint="Call it yourself at the bottom of your file with the same input and read the error.")


class _RealSleep(Exception):
    pass


def _send(ctx, label, body, key, expect=None, **kwargs):
    """Run the player's send() against the grader's Oracle; time.sleep is forbidden here."""
    _oracle(ctx)
    send = _fn(ctx, "send")
    real_sleep = time.sleep

    def forbidden(seconds):
        raise _RealSleep(seconds)

    time.sleep = forbidden
    try:
        result = send(json.loads(json.dumps(body)), key, **kwargs)
    except _RealSleep:
        raise Fail(f"`{label}` called time.sleep(). That makes YOU wait, and the Oracle's clock never moves.",
                   hint="Wait on the Oracle's clock instead: oracle_api.sleep(delay).")
    except Exception as exc:  # noqa: BLE001
        if expect and isinstance(exc, expect):
            return exc
        seen = _CACHE["mod"]._STATE["requests"]
        if expect and len(seen) == 1 and seen[0]["status"] in (400, 401):
            status = seen[0]["status"]
            raise Fail(f"`{label}` raised {type(exc).__name__}: {exc}. The Oracle answered {status}, "
                       f"so send must raise {expect.__name__}.",
                       hint=(f"Check the status: a 401 raises PermissionError (the key is bad), any other error "
                             f"except 429 raises ValueError. Both carry the server's error message."))
        detail = ""
        if seen:
            detail = f" The Oracle answered {[r['status'] for r in seen]}"
            errors = [r["error"] for r in seen if r.get("error")]
            detail += f', last error: "{errors[-1]}".' if errors else "."
        raise Fail(f"`{label}` raised {type(exc).__name__}: {exc}.{detail}",
                   hint="Print response.status and response.text inside send to see what the Oracle answered.")
    finally:
        time.sleep = real_sleep
    if expect:
        raise Fail(f"`{label}` returned {str(result)[:120]!r} instead of raising {expect.__name__}.")
    return result


def _valid_body(text: str = "Status report?", system: str = "You are terse.", max_tokens: int = 64) -> dict:
    return {"model": "oracle-1", "max_tokens": max_tokens, "system": system,
            "messages": [{"role": "user", "content": text}]}


def _text_of(payload) -> str:
    return "".join(b["text"] for b in payload["content"] if b.get("type") == "text")


# ── firewall layers ───────────────────────────────────────────────────────────

@MISSION.check("Credentials — `build_headers(api_key)`")
def _headers(ctx):
    build_headers = _fn(ctx, "build_headers")
    for key in ("nsk-test-1234", "sk-another-key-9"):
        got = _call(f"build_headers({key!r})", build_headers, key)
        want = {"x-api-key": key, "anthropic-version": API_VERSION, "content-type": "application/json"}
        if got is None:
            raise Fail(f"`build_headers({key!r})` returned None.", hint="return {\"x-api-key\": api_key, ...}")
        if not isinstance(got, dict):
            raise Fail(f"`build_headers({key!r})` returned {type(got).__name__}; headers are a dict.")
        missing = [k for k in want if k not in got]
        if missing:
            raise Fail(f"`build_headers({key!r})` is missing {missing}.",
                       hint="Header names are lower-case, with dashes: \"x-api-key\", \"anthropic-version\", \"content-type\".")
        for k, v in want.items():
            if got[k] != v:
                raise Fail(f"`build_headers({key!r})`[{k!r}] is {got[k]!r}, expected {v!r}.",
                           hint="Use the api_key parameter, not a fixed key.")
        if set(got) != set(want):
            raise Fail(f"`build_headers` sends extra headers {sorted(set(got) - set(want))}. Send exactly the three.")


@MISSION.check("Prompt templates — `fill_template(template, fields)`")
def _template(ctx):
    fill = _fn(ctx, "fill_template")
    cases = [("Hello {name}.", {"name": "Vex"}, "Hello Vex."),
             ("{a}-{b}-{a}", {"a": 1, "b": "x"}, "1-x-1"),
             ("Only {x} matters.", {"x": "this", "y": "ignored"}, "Only this matters."),
             ("No fields at all.", {}, "No fields at all.")]
    for template, fields, want in cases:
        label = f"fill_template({template!r}, {fields!r})"
        got = _call(label, fill, template, dict(fields))
        if got != want:
            raise Fail(f"`{label}` returned {got!r}, expected {want!r}.",
                       hint="template.format(**fields) fills every {name} from the dict.")
    template, fields = "Agent {name} reports {status}.", {"name": "Wren"}
    label = f"fill_template({template!r}, {fields!r})"
    try:
        got = fill(template, dict(fields))
    except ValueError as exc:
        if "status" not in str(exc):
            raise Fail(f"`{label}` raised ValueError({str(exc)!r}), but the message doesn't name the missing field 'status'.",
                       hint="Catch the KeyError as a variable and put it in the message: except KeyError as missing: ...")
        return
    except KeyError:
        raise Fail(f"`{label}` let a raw KeyError escape.",
                   hint="Catch it and raise ValueError(f\"template field missing: {missing}\") instead.")
    except Exception as exc:  # noqa: BLE001
        raise Fail(f"`{label}` raised {type(exc).__name__}, not ValueError.")
    raise Fail(f"`{label}` returned {got!r} even though the field 'status' is missing.",
               hint="str.format raises KeyError for a missing field; turn it into a ValueError.")


@MISSION.check("JSON body — `build_request(system, user_text, max_tokens=300)`")
def _request(ctx):
    build_request = _fn(ctx, "build_request")
    model = ctx.get("MODEL")
    if not isinstance(model, str) or not model.strip():
        raise Fail("`MODEL` must stay a non-empty string naming the model.")
    for args, kwargs, tokens in ((("You are terse.", "Status?"), {}, 300),
                                 (("Answer in haiku.", "Describe the Grid."), {"max_tokens": 64}, 64)):
        label = f"build_request({', '.join(map(repr, args))}{', max_tokens=64' if kwargs else ''})"
        got = _call(label, build_request, *args, **kwargs)
        want = {"model": model, "max_tokens": tokens, "system": args[0],
                "messages": [{"role": "user", "content": args[1]}]}
        if got is None:
            raise Fail(f"`{label}` returned None.", hint="Build the dict and return it.")
        if not isinstance(got, dict):
            raise Fail(f"`{label}` returned {type(got).__name__}; the body is a dict.")
        try:
            json.dumps(got)
        except TypeError as exc:
            raise Fail(f"`{label}` can't be turned into JSON: {exc}")
        for key in want:
            if key not in got:
                raise Fail(f"`{label}` has no {key!r} key.")
            if got[key] != want[key]:
                hint = ("messages is a LIST of dicts: [{\"role\": \"user\", \"content\": user_text}]"
                        if key == "messages" else f"{key} comes from {'MODEL' if key == 'model' else 'the parameter'}.")
                raise Fail(f"`{label}`[{key!r}] is {got[key]!r}, expected {want[key]!r}.", hint=hint)
        if set(got) != set(want):
            raise Fail(f"`{label}` has unexpected keys {sorted(set(got) - set(want))}.")


@MISSION.check("Content blocks — `parse_reply(payload)`")
def _parse(ctx):
    parse = _fn(ctx, "parse_reply")
    payloads = [
        {"content": [{"type": "text", "text": "Signal received."}]},
        {"content": [{"type": "thinking", "thinking": "..."}, {"type": "text", "text": "Two"},
                     {"type": "text", "text": " parts."}]},
        {"content": [{"type": "text", "text": "Before. "},
                     {"type": "tool_use", "id": "t1", "name": "scan", "input": {}},
                     {"type": "text", "text": "After."}], "stop_reason": "tool_use"},
        {"content": []},
    ]
    for payload in payloads:
        want = _text_of(payload)
        label = f"parse_reply({json.dumps(payload)[:90]}...)"
        got = _call(label, parse, json.loads(json.dumps(payload)))
        if got != want:
            hint = "Keep only blocks whose \"type\" is \"text\", and join their \"text\" with \"\".join(...)."
            if isinstance(got, str) and "..." in got and "..." not in want:
                hint = "A thinking block leaked into the answer. Filter by block[\"type\"] == \"text\"."
            raise Fail(f"`{label}` returned {got!r}, expected {want!r}.", hint=hint)


@MISSION.check("Corrupted client — `send` delivers, and refuses bad requests")
def _send_ok(ctx):
    oracle = _oracle(ctx)
    oracle.reset(throttle=0)
    body = _valid_body("Report the Grid's status.", "You are terse.", 77)
    got = _send(ctx, "send(body, key)", body, ORACLE_KEY)
    want = oracle.reply_for(body)
    if got != want:
        hint = "Return response.json(), the parsed dict, not response.text or the Response object."
        raise Fail(f"`send` returned {str(got)[:100]!r}; expected the Oracle's parsed JSON reply.", hint=hint)
    if len(oracle._STATE["requests"]) != 1:
        raise Fail(f"`send` made {len(oracle._STATE['requests'])} requests for one successful answer.")
    oracle.reset(throttle=0)
    bad = {"model": "oracle-1", "max_tokens": 5, "messages": []}
    _send(ctx, "send(body_with_no_messages, key)", bad, ORACLE_KEY, expect=ValueError)
    count = len(oracle._STATE["requests"])
    if count != 1:
        raise Fail(f"A 400 (malformed request) was retried: {count} requests. Sending the same broken body again "
                   "can't fix it.", hint="On any status other than 200 or 429, raise straight away.")


@MISSION.check("Corrupted client — a 401 raises PermissionError without retrying")
def _send_auth(ctx):
    oracle = _oracle(ctx)
    oracle.reset(throttle=0)
    _send(ctx, "send(body, revoked_key)", _valid_body(), REVOKED_KEY, expect=PermissionError)
    count = len(oracle._STATE["requests"])
    if count != 1:
        raise Fail(f"Your client retried a revoked key {count} times. A 401 never fixes itself; "
                   "real servers lock out keys that do this.",
                   hint="if response.status == 401: raise PermissionError(...) before any retry logic.")


@MISSION.check("Corrupted client — 429s get exponential backoff, then give up")
def _send_backoff(ctx):
    oracle = _oracle(ctx)
    scenarios = [(3, 1, 4, [1.0, 2.0, 4.0], True), (2, 5, 4, [5.0, 5.0], True), (9, 1, 3, [1.0, 2.0, 4.0], False)]
    for throttle, retry_after, retries, want_sleeps, succeeds in scenarios:
        oracle.reset(throttle=throttle, retry_after=retry_after)
        label = f"send(...) with {throttle} rate limits (retry-after {retry_after}), max_retries={retries}"
        if succeeds:
            got = _send(ctx, label, _valid_body(), ORACLE_KEY, max_retries=retries)
            if not isinstance(got, dict) or got.get("type") != "message":
                raise Fail(f"`{label}` should eventually return the Oracle's reply, got {str(got)[:80]!r}.")
        else:
            _send(ctx, label, _valid_body(), ORACLE_KEY, expect=RuntimeError, max_retries=retries)
        state = oracle._STATE
        if state["early"]:
            raise Fail(f"`{label}`: you retried before retry-after had passed on the Oracle's clock.",
                       hint="Wait max(2 ** attempt, float(response.headers[\"retry-after\"])) with oracle_api.sleep.")
        sleeps = state["sleeps"]
        if not succeeds and len(state["requests"]) != retries + 1:
            raise Fail(f"`{label}` made {len(state['requests'])} requests; max_retries={retries} allows exactly "
                       f"{retries + 1} (the first try plus {retries} retries).")
        if len(sleeps) == len(want_sleeps) + 1 and not succeeds and \
                all(math.isclose(a, b) for a, b in zip(sleeps, want_sleeps)):
            raise Fail(f"`{label}` waited once more after the final attempt ({sleeps}).",
                       hint="When attempt == max_retries, raise RuntimeError instead of sleeping.")
        if len(sleeps) != len(want_sleeps) or not all(math.isclose(a, b) for a, b in zip(sleeps, want_sleeps)):
            raise Fail(f"`{label}` waited {sleeps}; expected {want_sleeps}.",
                       hint="Exponential backoff: 2 ** attempt (1, 2, 4...), but never less than retry-after.")


@MISSION.check("Key hygiene — loaded from oracle.key, never in source")
def _key(ctx):
    if ORACLE_KEY in ctx.source:
        raise Fail("The Oracle key is pasted into your source code. Anyone who sees this file now owns your key.",
                   hint='Read it from the chip:  with open("oracle.key") as f: api_key = f.read().strip()')
    api_key = ctx.get("api_key")
    if not isinstance(api_key, str) or not api_key:
        raise Fail("`api_key` is empty.", hint='with open("oracle.key") as f: api_key = f.read().strip()')
    if api_key == ORACLE_KEY + "\n" or api_key.strip() == ORACLE_KEY != api_key:
        raise Fail("`api_key` still has whitespace or a newline around it, so the Oracle will reject it.",
                   hint="Call .strip() on what you read from the file.")
    if api_key != ORACLE_KEY:
        raise Fail("`api_key` doesn't match the key on the chip.", hint="Read the file oracle.key next to your mission file.")


@MISSION.check("Open the channel — ask the Core what it learned")
def _channel(ctx):
    callsign = ctx.get("CALLSIGN")
    if not isinstance(callsign, str) or not callsign.strip():
        raise Fail("`CALLSIGN` is empty. The Oracle should know who's asking.", hint='CALLSIGN = "Nyx"')
    boot = _boot_requests(ctx)
    answered = [r for r in boot if r.get("status") == 200]
    if not answered:
        statuses = [r.get("status") for r in boot]
        raise Fail(f"Your script never got a 200 from the Oracle (statuses seen: {statuses or 'no requests'}).",
                   hint="At the bottom: response = send(body, api_key), then parse it. Fix the earlier layers first.")
    data = json.loads(answered[-1]["body"])
    want_system = SYSTEM_TEMPLATE.format(callsign=callsign, order="Order of the Source", style="one paragraph")
    if data.get("system") != want_system or data.get("messages") != [{"role": "user", "content": QUESTION}]:
        raise Fail("The request that reached the Oracle wasn't built from SYSTEM_TEMPLATE, your CALLSIGN and QUESTION.",
                   hint="Keep the starter's fields / system_prompt / body lines and send `body`.")
    want = _text_of(_oracle(ctx).reply_for(data))
    reply = ctx.get("reply_text")
    if not any(isinstance(n, ast.Call) for v in ctx.assignments("reply_text") for n in ast.walk(v)):
        raise Fail("`reply_text` must come from parsing the Oracle's response, not typed in.",
                   hint="reply_text = parse_reply(response)")
    if reply != want:
        raise Fail(f"`reply_text` is {str(reply)[:90]!r}..., not the Oracle's answer.",
                   hint="reply_text = parse_reply(send(body, api_key))")
    if want not in ctx.stdout:
        raise Fail("The Oracle answered, but you didn't print its reply.", hint="print(reply_text)")
    ctx.export("oracle_token", want.rsplit("Channel token: ", 1)[-1].rstrip("."))
